twig:
    default_path: '%kernel.project_dir%/templates'
    # On utilise Bootstrap sur nos formulaires
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        # Le @ permet de donner une instance d'un service
        cart: '@App\Services\SuperCart'
